#!/bin/bash
#SBATCH --job-name="treecode benchmark"
#SBATCH -A C3SE2024-2-18 -p vera #Check if correct project
#SBATCH -t 0-00:30:00
#SBATCH --output=output_treecode_benchmark%j.txt
#SBATCH --cpus-per-task=1 # OpenMP threads per MPI rank
#SBATCH --gpus-per-node=H100:1

input_file=$1  # opting to also take the file as an input argument

eval `head -n $SLURM_ARRAY_TASK_ID $input_file | tail -1`


export OMP_NUM_THREADS=1 # Set number of OpenMP threads per MPI rank
module load OpenMPI/5.0.3-GCC-13.3.0-aocc
module load CUDA/12.6.0

srun ../build/treecode nbody=1000000 mpi_depth=8 tstop=0.3125 omp_threshold=999 benchmark=CudaBenchmark.txt random_seed=true CUDA_STREAMS=$CUDA_STREAMS CUDA_SIZE=$CUDA_SIZE