image: docker

services:
  - name: docker:dind

stages:
  - test


verification-test:
  stage: test
  tags:
    - docker-build
  script:
    - docker build -t treecode .
    - docker run treecode ./tools/verifyOutput.sh
