default:
  image: docker:25.0.5
  services:
    - docker:25.0.5-dind
  before_script:
    - docker info



build:
  stage: build
  script:
    - docker build -t treecode .


test:
  stage: test
  script:
    - docker run treecode ./tools/verifyOutput.sh



