#!/bin/bash
#SBATCH --job-name=treecode
#SBATCH -A C3SE2024-2-18 -p vera #Check if correct project
#SBATCH -t 0-00:05:00 #Max runtime of 5 min
#SBATCH --output=output_%j.txt
#SBATCH --nodes=4 # Number of nodes
#SBATCH --ntasks-per-node=4 # 4 MPI tasks (ranks) per node
#SBATCH --cpus-per-task=8 # 8 OpenMP threads per MPI rank
export OMP_NUM_THREADS=8 # Set number of OpenMP threads per MPI rank

srun ./treecode nbody=100000 tstop=1