#!/bin/bash
#SBATCH --job-name=treecode
#SBATCH -A C3SE2024-2-18 -p vera #Check if correct project
#SBATCH -t 0-00:20:00 #Max runtime of 20 min
#SBATCH --output=output_mpi_depth_data%j.txt
#SBATCH --nodes=4 # Number of nodes
#SBATCH --ntasks-per-node=4 # 4 MPI tasks (ranks) per node
#SBATCH --cpus-per-task=1 # 1 OpenMP threads per MPI rank
export OMP_NUM_THREADS=1 # Set number of OpenMP threads per MPI rank

module load openmpi*****


srun ./treecode nbody=100000 mpi_depth=5 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=100000 mpi_depth=6 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=100000 mpi_depth=7 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=100000 mpi_depth=8 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=100000 mpi_depth=9 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=100000 mpi_depth=10 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=100000 mpi_depth=11 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=100000 mpi_depth=12 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt

srun ./treecode nbody=300000 mpi_depth=5 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=300000 mpi_depth=6 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=300000 mpi_depth=7 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=300000 mpi_depth=8 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=300000 mpi_depth=9 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=300000 mpi_depth=10 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=300000 mpi_depth=11 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=300000 mpi_depth=12 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt


srun ./treecode nbody=500000 mpi_depth=5 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=500000 mpi_depth=6 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=500000 mpi_depth=7 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=500000 mpi_depth=8 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=500000 mpi_depth=9 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=500000 mpi_depth=10 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=500000 mpi_depth=11 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
srun ./treecode nbody=500000 mpi_depth=12 tstop=1 omp_threshold=0 benchmark=mpi_depth_data.txt
